# Generated by Django 4.0.4 on 2022-06-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(max_length=100)),
                ('delivery_timeframe', models.CharField(max_length=15)),
                ('delivery_window', models.CharField(max_length=20)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delivery_method', models.CharField(max_length=20, verbose_name=[('IS', 'In Store'), ('HD', 'Home Delivery'), ('DD', 'Digital Delivery')])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
