# Generated by Django 4.0.4 on 2022-06-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_method',
            field=models.CharField(max_length=255, verbose_name=[('IS', 'In Store'), ('HD', 'Home Delivery'), ('DD', 'Digital Delivery')]),
        ),
    ]
